sonar.projectKey=arenahub-app_backend
sonar.organization=arenahub-app
sonar.host.url=https://sonarcloud.io

sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.java.test.binaries=target/test-classes

sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

sonar.exclusions=\
  **/ArenahubApplication.java,\
  **/dto/**,\
  **/exception/**,\
  **/*Properties.java,\
  **/vo/**,\
  **/config/**

sonar.cpd.exclusions=\
  **/dto/**,\
  **/exception/**,\
  **/vo/**
